/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Client;
import MainRun.MainRun;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.StringMessage;
import model.User;

/**
 *
 * @author lcmin
 */
public class ChatRoomFrm extends javax.swing.JFrame {
    int idroom =1;
    /**
     * Creates new form ChatRoomFrm
     */
    public ChatRoomFrm(int id) throws IOException {
        initComponents();
        idroom = id;
        setTable(MainRun.user.SearchRoomById(idroom).getUsersInRoom());
        fillmess();
    }

    private ChatRoomFrm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area_mess = new javax.swing.JTextArea();
        btn_send = new javax.swing.JButton();
        txt_send = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_adduser = new javax.swing.JButton();
        txt_usernamefr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Area_searchmess = new javax.swing.JTextArea();
        btn_return = new javax.swing.JButton();
        txt_searchmess = new javax.swing.JTextField();
        btn_searchmess = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_logoutroom = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_user.setBackground(new java.awt.Color(102, 255, 204));
        table_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_user.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_user);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 250, 140));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ten Phong");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, 40));

        Area_mess.setColumns(20);
        Area_mess.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Area_mess.setRows(5);
        jScrollPane2.setViewportView(Area_mess);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 380, 350));

        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        jPanel1.add(btn_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 80, -1));
        jPanel1.add(txt_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thanh vien");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 160, -1));

        btn_adduser.setText("Them Thanh vien");
        btn_adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adduserActionPerformed(evt);
            }
        });
        jPanel1.add(btn_adduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));
        jPanel1.add(txt_usernamefr, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 210, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 60, 20));

        Area_searchmess.setColumns(20);
        Area_searchmess.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Area_searchmess.setRows(5);
        jScrollPane3.setViewportView(Area_searchmess);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 350, 280, 200));

        btn_return.setText("return");
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });
        jPanel1.add(btn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 140, 30));
        jPanel1.add(txt_searchmess, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 210, -1));

        btn_searchmess.setText("Tim tin nhan");
        btn_searchmess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchmessActionPerformed(evt);
            }
        });
        jPanel1.add(btn_searchmess, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 630, 110, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Message");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 60, 20));

        btn_logoutroom.setText("Thoat Phong");
        btn_logoutroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutroomActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logoutroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 700, 120, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/d3ecbzg-045f95bb-8610-4dbb-84ab-e1d08fb037d7.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
        if(txt_send.getText()=="") JOptionPane.showMessageDialog(this,"vui long nhap tin nhan");
        else{
            int idserial = 0;
            for(int i=0;i<MainRun.user.getRoomsIn().size();i++){
            if(MainRun.user.getRoomsIn().get(i).getId()==idroom){
               if(MainRun.user.getRoomsIn().get(i).getStringMessages().size()!=0) {
                    idserial =  MainRun.user.getRoomsIn().get(i).getStringMessages().get(MainRun.user.getRoomsIn().get(i).getStringMessages().size()-1).getSerial()+1;
                    break;}
            }
            
            StringMessage stringMessage = new StringMessage();
            stringMessage.setUserName(MainRun.user.getUsername());
            stringMessage.setSerial(idserial);
            stringMessage.setContent(txt_send.getText());
            
            this.addmess(stringMessage);
            for(int j=0;j<MainRun.user.getRoomsIn().size();j++){
            if(MainRun.user.getRoomsIn().get(j).getId()==idroom){
                MainRun.user.getRoomsIn().get(j).getStringMessages().add(stringMessage);
                break;
            }
            }
            
            }
           
            try {
                MainRun.controller.write("Chat,"+idroom+","+idserial+","+txt_send.getText());
            } catch (IOException ex) {
                Logger.getLogger(ChatRoomFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         txt_send.setText("");
    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainRun.user.SearchRoomById(idroom).getStringMessages().clear();
        MainRun.user.SearchRoomById(idroom).getUsersInRoom().clear();
        Client.roomFrm = new RoomFrm();
        Client.roomFrm.setLocationRelativeTo(null);
        Client.roomFrm.setVisible(true);
    }//GEN-LAST:event_btn_returnActionPerformed

    private void btn_adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adduserActionPerformed
        try {
            // TODO add your handling code here:
            String s = txt_usernamefr.getText();
            if(s.length()>0){
            MainRun.controller.write("AddMember,"+idroom+","+txt_usernamefr.getText());
            User user = new User();
            user.setUsername(txt_usernamefr.getText());
            MainRun.user.SearchRoomById(idroom).getUsersInRoom().add(user);
            txt_usernamefr.setText("");
            this.setTable(MainRun.user.SearchRoomById(idroom).getUsersInRoom());}
        } catch (IOException ex) {
            Logger.getLogger(ChatRoomFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_adduserActionPerformed

    private void btn_logoutroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutroomActionPerformed
        try {
            // TODO add your handling code here:
            MainRun.controller.write("LeaveRoom,"+idroom);
        } catch (IOException ex) {
            Logger.getLogger(ChatRoomFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=0;i<MainRun.user.getRoomsIn().size();i++){
            if(MainRun.user.getRoomsIn().get(i).getId()==idroom){
                MainRun.user.getRoomsIn().remove(i);
                break;
            }
        }
        this.dispose();
        Client.roomFrm = new RoomFrm();
        Client.roomFrm.setLocationRelativeTo(null);
        Client.roomFrm.setVisible(true);
    }//GEN-LAST:event_btn_logoutroomActionPerformed

    private void btn_searchmessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchmessActionPerformed
        // TODO add your handling code here:
        Area_searchmess.setText("");
        String mess = txt_searchmess.getText();
        txt_searchmess.setText("");
        for(int i=0;i<MainRun.user.SearchRoomById(idroom).getStringMessages().size();i++){
            if(MainRun.user.SearchRoomById(idroom).getStringMessages().get(i).getContent().contains(mess) || mess.contains(MainRun.user.SearchRoomById(idroom).getStringMessages().get(i).getContent())){
                 String s = MainRun.user.SearchRoomById(idroom).getStringMessages().get(i).getUserName()+" :"+MainRun.user.SearchRoomById(idroom).getStringMessages().get(i).getContent();
                    s = s+"\n";
                    Area_searchmess.append(s);
            }
        }
        Area_searchmess.setWrapStyleWord(true);
        Area_searchmess.setLineWrap(true);
        Area_searchmess.setEditable(false);
    }//GEN-LAST:event_btn_searchmessActionPerformed
    public void setTable(ArrayList<User> users) throws IOException{
         String[] columnNames = {"username"};
         String[][] value = new String[users.size()][1];
         for(int i=0;i<users.size();i++){
             value[i][0] = users.get(i).getUsername()+"";
         }
         DefaultTableModel tablemodel = new DefaultTableModel(value,columnNames){
         public boolean isCellEdittable(int row,int column){
             return false;
         }
         };
         table_user.setModel(tablemodel);
         table_user.setEditingColumn(0);
         table_user.setEditingRow(0);
    }
    public boolean  checkOnline(String username){
        boolean check = false;
        for(int i=0;i<MainRun.user.getFriends().size();i++){
            if(MainRun.user.getUsername().equals(username)) {check = MainRun.user.getIsOnline();break;}
        
        }
        return check;
    }
    public void fillmess(){
        for(int i=0;i<MainRun.user.getRoomsIn().size();i++){
            if(MainRun.user.getRoomsIn().get(i).getId()==idroom){
                for(int j=0;j<MainRun.user.getRoomsIn().get(i).getStringMessages().size();j++){
                    String s = MainRun.user.getRoomsIn().get(i).getStringMessages().get(j).getUserName()+" :"+MainRun.user.getRoomsIn().get(i).getStringMessages().get(j).getContent();
                    s = s+"\n";
                    Area_mess.append(s);
                }
            }
        }
        Area_mess.setWrapStyleWord(true);
        Area_mess.setLineWrap(true);
        Area_mess.setEditable(false);
    }
    public void addmess(StringMessage stringMessage){
        String s = stringMessage.getUserName()+" :"+stringMessage.getContent();
        Area_mess.append(s+"\n");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatRoomFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatRoomFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatRoomFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatRoomFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatRoomFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area_mess;
    private javax.swing.JTextArea Area_searchmess;
    private javax.swing.JButton btn_adduser;
    private javax.swing.JButton btn_logoutroom;
    private javax.swing.JButton btn_return;
    private javax.swing.JButton btn_searchmess;
    private javax.swing.JButton btn_send;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_user;
    private javax.swing.JTextField txt_searchmess;
    private javax.swing.JTextField txt_send;
    private javax.swing.JTextField txt_usernamefr;
    // End of variables declaration//GEN-END:variables
}
